# Generated by Django 4.1.5 on 2023-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0002_productstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogheadlinetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
