# Generated by Django 4.1.5 on 2023-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0005_productstable_productprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogheadlinetable',
            old_name='blogContent',
            new_name='blogContent1',
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogContent2',
            field=models.CharField(default='null', max_length=2500),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogContent3',
            field=models.CharField(default='null', max_length=2500),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogContent4',
            field=models.CharField(default='null', max_length=2500),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogHeading',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogSubHeading1',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogSubHeading2',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogSubHeading3',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
