# Generated by Django 4.1.5 on 2023-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogHeadlineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=255)),
                ('blogSummary', models.CharField(max_length=255)),
                ('blogAuthor', models.CharField(max_length=255)),
            ],
        ),
    ]
