# Generated by Django 4.1.5 on 2023-09-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0003_alter_blogheadlinetable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogContent',
            field=models.CharField(default='null', max_length=2500),
        ),
    ]
