# Generated by Django 4.1.5 on 2023-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0004_blogheadlinetable_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='productPrice',
            field=models.IntegerField(default=0, max_length=13),
        ),
    ]
