# Generated by Django 4.1.5 on 2023-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0007_rename_blogcontent1_blogheadlinetable_blogcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogSummary',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
