# Generated by Django 4.1.5 on 2023-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0011_blogheadlinetable_blogimagelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstable',
            name='productPrice',
            field=models.IntegerField(default=0),
        ),
    ]
