# Generated by Django 4.1.5 on 2023-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0006_rename_blogcontent_blogheadlinetable_blogcontent1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogheadlinetable',
            old_name='blogContent1',
            new_name='blogContent',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogAuthor',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogContent2',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogContent3',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogContent4',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogHeading',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogSubHeading1',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogSubHeading2',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogSubHeading3',
        ),
        migrations.RemoveField(
            model_name='blogheadlinetable',
            name='blogSummary',
        ),
        migrations.AlterField(
            model_name='blogheadlinetable',
            name='blogTitle',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogheadlinetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
