# Generated by Django 4.1.5 on 2023-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0008_blogheadlinetable_blogsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogheadlinetable',
            name='blogContent1',
            field=models.CharField(default='null', max_length=2500),
        ),
    ]
