# Generated by Django 4.1.5 on 2023-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessApp1', '0012_alter_productstable_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='productImageLinks',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
